### ISSUE TITLE
Sigh does not choose correct certificate when creating/updating provisioning

### ISSUE THREAD

**Issue by robwithhair** [fastlane/sigh#122]
I am using fastlane with Cert and Sigh and I am getting the following error in deliver in a previously working build script.
```

⌦  Code Sign error: No codesigning identities found: No codesigning identities (i.e. certificate and private key pairs) that match the provisioning profile specified in your build settings (“com.iKebabs.waterdal AppStore”) were found.


    no rule to process file '/Users/Shared/Jenkins/Home/jobs/iOS Build - Release Automation/workspace/iOS/Framework/Plugins/ChildBrowser/README.md' of type net.daringfireball.markdown for architecture armv7
    no rule to process file '/Users/Shared/Jenkins/Home/jobs/iOS Build - Release Automation/workspace/iOS/Framework/Plugins/ChildBrowser/README.md' of type net.daringfireball.markdown for architecture arm64

⌦  CodeSign error: code signing is required for product type 'Application' in SDK 'iOS 8.3'


** ARCHIVE FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
[0m
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.4.0/lib/fastlane/actions/ipa.rb:94:in `rescue in run': [31mA build error occured, this is usually related to code signing. Take a look at the error above[0m (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.4.0/lib/fastlane/actions/ipa.rb:66:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.4.0/lib/fastlane/fast_file.rb:112:in `block (2 levels) in method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.4.0/lib/fastlane/actions/actions_helper.rb:51:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.4.0/lib/fastlane/fast_file.rb:94:in `block in method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.4.0/lib/fastlane/fast_file.rb:93:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.4.0/lib/fastlane/fast_file.rb:93:in `method_missing'
	from (eval):58:in `block (2 levels) in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.4.0/lib/fastlane/runner.rb:39:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.4.0/lib/fastlane/runner.rb:39:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.4.0/lib/fastlane/runner.rb:29:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.4.0/lib/fastlane/runner.rb:29:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.4.0/lib/fastlane/lane_manager.rb:33:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.4.0/bin/fastlane:39:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.4.0/bin/fastlane:128:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.4.0/bin/fastlane:134:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
[31m[17:11:32]: [0m[33mA build error occured. This can have many reasons, usually[0m
[31m[17:11:32]: [0m[33mit has something to do with code signing. The `ipa` action[0m
[31m[17:11:32]: [0m[33muses `shenzhen` under the hood: https://github.com/nomad/shenzhen[0m
[31m[17:11:32]: [0m[33mThe command that was used by fastlane:[0m
[31m[17:11:32]: [0m[33mkrausefx-ipa build -s "Framework" -m "/Users/Shared/Jenkins/Home/jobs/iOS Build - Release Automation/workspace/iOS/AppStore_com.iKebabs.waterdal.mobileprovision" --verbose | xcpretty[0m
[31m[17:11:32]: [0m[33m-------------------------------------------------------[0m
```

This seems to possibly be to do with sigh using/creating a provisioning profile which has been signed with a distribution key which is not on the build server.  It isn't checking/using the one from cert.

Running 

```
  increment_build_number( build_number: "672" )
  produce({
        produce_app_identifier_suffix: "",
        produce_app_name: "Waterdales Kebab House",
        produce_language: "UK English",
        produce_version: "1.0",
        produce_sku: "waterdal",
        produce_team_name: "Savas Saglam"
  })
  cert
  sh "pem"
  sigh( force: true )
  snapshot
  update_project_code_signing( path: "Framework.xcodeproj")
  ipa({
    scheme: "Framework"
  })
  deliver(
    skip_deploy: true,
    force: true
  )
```

This is my output from Cert and Sigh

```
[37m[17:09:06]: [0m[32m------------------[0m
[37m[17:09:06]: [0m[32m--- [0m[32mStep: cert[0m[32m ---[0m
[37m[17:09:06]: [0m[32m------------------[0m
[37m[17:09:06]: [0mLogin into iOS Developer Center
[37m[17:09:10]: [0mDownloading URL: 'https://developer.apple.com/account/ios/certificate/certificateContentDownload.action?displayId=7AEM4BJL26&type=R58UK2EWSO'
[37m[17:09:12]: [0mDownloading URL: 'https://developer.apple.com/account/ios/certificate/certificateContentDownload.action?displayId=59CLB3YM29&type=R58UK2EWSO'
[37m[17:09:14]: [0m[32mFound the certificate 59CLB3YM29-R58UK2EWSO which is installed on the local machine. Using this one.[0m
[37m[17:09:15]: [0m[32mUse signing certificate '59CLB3YM29' from now on![0m
[37m[17:09:15]: [0m[32m------------------[0m
[37m[17:09:15]: [0m[32m--- [0m[32mStep: sigh[0m[32m ---[0m
[37m[17:09:15]: [0m[32m------------------[0m
[37m[17:09:15]: [0mStarting login
Logging spaceship web requests to '/tmp/spaceship.log'
[37m[17:09:17]: [0mSuccessfully logged in
[37m[17:09:17]: [0m[33mFound 1 matching profile(s)[0m
[37m[17:09:17]: [0m[33mUpdating the provisioning profile[0m
[37m[17:09:21]: [0m[33mDownloading provisioning profile...[0m
[37m[17:09:22]: [0m[32mSuccessfully downloaded provisioning profile...[0m
[37m[17:09:22]: [0m[32mProvisioning profile of app 'Waterdales Kebab House' with the name 'com.iKebabs.waterdal AppStore' successfully analysed.[0m
[37m[17:09:22]: [0mInstalling provisioning profile...
[37m[17:09:22]: [0m[32mProfile successfully installed[0m
[32m./AppStore_com.iKebabs.waterdal.mobileprovision[0m
```
If I am understanding the output correctly it seems like it is using the certificate which exists on the machine in cert and uses that for code signing but the provisioning profile was created by sigh with a deployment certificate which was not the one which cert created.  It's using an old one.  So code signing is failing as provisioning doesn't match certificate from cert.  What do you think.  Does this sound plausible?  I have checked the provisioning profile and it does indeed seem to be the old certificate which it is being used.

**Comment by robwithhair** [comment]
I am going to try and switch the provisioning profile to use the new certificate and run the build server again to see if it now works ok.  This is for the purpose of debugging.

**Comment by robwithhair** [comment]
I updated the provisioning profile so that it was using the same cert as Cert and it worked fine so this must be an issue with sigh.  This profile was created by sigh on this build server so it could do with a check on profile re-use and to ensure it is created with the same cert as the one made/used by Cert.

**Comment by robwithhair** [comment]
Just to confirm, it seems Sigh also doesn't check if the certificate is revoked before continuing to use the provisioning profile.  On my machine it seems it's still using a profile, rather than recreating if the certificate has been revoked.  @KrauseFx any luck with this issue Felix?

**Comment by KrauseFx** [comment]
I'll add a check that the profile is valid, it seems like `sigh` doesn't do that right now.

**Comment by KrauseFx** [comment]
Added with https://github.com/KrauseFx/sigh/commit/f538f8952c90fe1920f14f51b4b065f69f73ca72, I'll publish a new release soon

**Comment by robwithhair** [comment]
Thanks Felix

**Comment by KrauseFx** [comment]
@robwithhair the new version of `sigh` is now available :+1:

**Comment by robwithhair** [comment]
Thanks @KrauseFx, I'm testing now.  I notice jenkins/fastlane is saying there are updates available to produce and pem, but I've run sudo gem update and sudo gem cleanup.  When i run produce -v from command line it says it's on the most recent version but when I run through fastlane it says I need to update.  Bit odd.

**Comment by KrauseFx** [comment]
@robwithhair sorry, I need more details. What versions do you have installed?

**Comment by robwithhair** [comment]
```
buildserver:.ssh robwithhair$ produce -v
produce 0.3.5
buildserver:.ssh robwithhair$ fastlane -v
fastlane 1.6.0
buildserver:.ssh robwithhair$ pem -v
pem 0.6.4
```

**Comment by KrauseFx** [comment]
Those are all the latest versions. And you get an update message when running those tools with `fastlane`?

**Comment by robwithhair** [comment]
Yeah.  That's odd.

**Comment by robwithhair** [comment]
Solved after reboot.  Server playing silly games.  Apologies.

**Comment by robwithhair** [comment]
This is still causing problems in the most recent sigh build

**Comment by robwithhair** [comment]
if 3 certs and a provisioning profile exist on the dev centre and 1 cert is installed on the local machine then sigh will not recreate the provisioning profile using the cert which the server has, the one used by cert.  This means code signing fails later on.  
```
[37m[14:14:33]: [0m[32m------------------[0m
[37m[14:14:33]: [0m[32m--- [0m[32mStep: sigh[0m[32m ---[0m
[37m[14:14:33]: [0m[32m------------------[0m
[37m[14:14:33]: [0mStarting login
Logging spaceship web requests to '/tmp/spaceship.log'
[37m[14:14:35]: [0mSuccessfully logged in
[37m[14:14:36]: [0m[33mFound 1 matching profile(s)[0m
[37m[14:14:36]: [0m[33mUpdating the provisioning profile[0m
[37m[14:14:39]: [0m[33mDownloading provisioning profile...[0m
[37m[14:14:40]: [0m[32mSuccessfully downloaded provisioning profile...[0m
[37m[14:14:40]: [0m[32mProvisioning profile of app 'saibaba' with the name 'saibaba' successfully analysed.[0m
[37m[14:14:40]: [0mInstalling provisioning profile...
[37m[14:14:40]: [0m[32mProfile successfully installed[0m
[32m./AppStore_com.Sriram.saibaba.mobileprovision[0m
[37m[14:14:40]: [0m[SHELL COMMAND]: [33mgit -C .. apply fastlane/stopAskLocation.patch[0m
[37m[14:14:40]: [0m[SHELL]: iOS/fastlane/stopAskLocation.patch:58: new blank line at EOF.
[37m[14:14:40]: [0m[SHELL]: +
[37m[14:14:40]: [0m[SHELL]: warning: 1 line adds whitespace errors.
```
it will download and use the provisioning profile even though the signing cert isn't on the local machine, only on the dev centre.

**Comment by KrauseFx** [comment]
@robwithhair confirmed, it seems like `sigh` doesn't verify that existing provisioning profiles are from a code signing identity that's installed on the current machine.

**Comment by KrauseFx** [comment]
The new version of `sigh` verifies this, please update and let me know if that works for you :+1:

**Comment by robwithhair** [comment]
Thanks Felix.  As this is a fairly tricky situation to replicate but one we'll undoubtable run into again soon, I will close and re-open if this continues to be an issue if that works for you?  Thanks for the update.

**Comment by KrauseFx** [comment]
Thanks, sounds great! :+1:

**Comment by robwithhair** [comment]
Hey Felix, 

We are still seeing this issue on a completely up-to-date version of the tools.  

![image](https://cloud.githubusercontent.com/assets/6692245/9246912/f3599a44-41a6-11e5-8bb5-d522e98432a3.png)

Sigh used wrong certificate

```
[37m[10:04:42]: [0m[32m------------------[0m
[37m[10:04:42]: [0m[32m--- [0m[32mStep: cert[0m[32m ---[0m
[37m[10:04:42]: [0m[32m------------------[0m
[37m[10:04:42]: [0mStarting login
[37m[10:04:45]: [0mSuccessfully logged in
[37m[10:05:01]: [0m[32mFound the certificate 5LGZEX95R3 (SwiftBiz Limited) which is installed on the local machine. Using this one.[0m
[37m[10:05:08]: [0m[32mUse signing certificate '5LGZEX95R3' from now on![0m
```

```
[37m[10:05:08]: [0m[32m------------------[0m
[37m[10:05:08]: [0m[32m--- [0m[32mStep: sigh[0m[32m ---[0m
[37m[10:05:08]: [0m[32m------------------[0m
[37m[10:05:08]: [0mStarting login
[37m[10:05:10]: [0mSuccessfully logged in
[37m[10:05:11]: [0m[33mFound 1 matching profile(s)[0m
[37m[10:05:11]: [0m[33mUpdating the provisioning profile[0m
[37m[10:05:14]: [0m[33mDownloading provisioning profile...[0m
[37m[10:05:14]: [0m[32mSuccessfully downloaded provisioning profile...[0m
[37m[10:05:14]: [0m[32mProvisioning profile of app 'crmswift' with the name 'crmswift' successfully analysed.[0m
[37m[10:05:14]: [0mInstalling provisioning profile...
[37m[10:05:14]: [0m[32mProfile successfully installed[0m
[32m./AppStore_com.SwiftBiz.crmswift.mobileprovision[0m
```

![image](https://cloud.githubusercontent.com/assets/6692245/9246968/758da776-41a7-11e5-9e33-14aeea922ba1.png)

**Comment by robwithhair** [comment]
notifying @KrauseFx

**Comment by robwithhair** [comment]
Even when I add the other certificate to the build server the build still fails.  Is this because cert is choosing the certificate with the most time remaining on it and it's not matching the provisioning profile sigh is supplying.

**Comment by robwithhair** [comment]
Should we be moving to gym from shenzhen?  Could this affect building?  I know we tried our script with xcbuild before and had issues, had to revert to shenzhen again.

**Comment by KrauseFx** [comment]
@robwithhair about `gym`, I'd recommend to wait another 1-2 weeks before upgrading.
Did I get this correctly: The provisioning profile is already there, but uses a code signing identity which isn't installed on the local machine? `sigh` should verify the certificate is available and only choose the profile if it's there.

**Comment by robwithhair** [comment]
I can confirm that what seems to happen is that even though both certificates were in the keychain cert chose to use the one which the provisioning profile wasn't made against.  Then sigh chose not to recreate the provisioning profile even though cert chose to use the other certificate.

**Comment by robwithhair** [comment]
on developer portal I switched the profile to the other certificate and build worked fine first time, even though the build server had both certificates.

**Comment by robwithhair** [comment]
@KrauseFx I don't know if sigh made the original profile or if it was already generated, I'll check.

**Comment by robwithhair** [comment]
@KrauseFx in the output above sigh says that it's updating the profile but seemingly with the wrong certificate?

**Comment by robwithhair** [comment]
@KrauseFx this is the output form the first build.  At this point the server had a valid certificate and chose to use that.  You'll see sigh says it's updated and downloaded the provisioning profile but used the wrong certificate.  Then it failed due to code signing.

```
[37m[10:04:42]: [0m[32m------------------[0m
[37m[10:04:42]: [0m[32m--- [0m[32mStep: cert[0m[32m ---[0m
[37m[10:04:42]: [0m[32m------------------[0m
[37m[10:04:42]: [0mStarting login
[37m[10:04:45]: [0mSuccessfully logged in
[37m[10:05:01]: [0m[32mFound the certificate 5LGZEX95R3 (SwiftBiz Limited) which is installed on the local machine. Using this one.[0m
[37m[10:05:08]: [0m[32mUse signing certificate '5LGZEX95R3' from now on![0m
[37m[10:05:08]: [0m[32m------------------[0m
[37m[10:05:08]: [0m[32m--- [0m[32mStep: sigh[0m[32m ---[0m
[37m[10:05:08]: [0m[32m------------------[0m
[37m[10:05:08]: [0mStarting login
[37m[10:05:10]: [0mSuccessfully logged in
[37m[10:05:11]: [0m[33mFound 1 matching profile(s)[0m
[37m[10:05:11]: [0m[33mUpdating the provisioning profile[0m
[37m[10:05:14]: [0m[33mDownloading provisioning profile...[0m
[37m[10:05:14]: [0m[32mSuccessfully downloaded provisioning profile...[0m
[37m[10:05:14]: [0m[32mProvisioning profile of app 'crmswift' with the name 'crmswift' successfully analysed.[0m
[37m[10:05:14]: [0mInstalling provisioning profile...
[37m[10:05:14]: [0m[32mProfile successfully installed[0m
[32m./AppStore_com.SwiftBiz.crmswift.mobileprovision[0m
```

Then I added the other certificate so cert had two to choose from.  Build failed due to code signing again.

Then I switched on the dev portal to use other certificate, and it worked first time.

**Comment by robwithhair** [comment]
@KrauseFx Still getting this error.  This time a certificate was created by cert and Sigh when updating the provisioning profile didn't set the correct certificate.

**Comment by robwithhair** [comment]
Hey @KrauseFx any update on this issue?  It's causing quite a bit of confusion amongst the build team.

**Comment by robwithhair** [comment]
Definitely something that's worked in the past and since going to spaceship has stopped working correctly.

**Comment by DenHeadless** [comment]
@KrauseFx I can confirm this happens on latest Fastlane, sigh and cert.

Steps to reproduce
1. Have a valid certificate and provisioning profile with that certificate
2. run cert and sigh with force -> New certificate is created, however provisioning profile is signed with the first one.

All environment variables look fine. Temporary workaround for now is to *delete* provisioning profile from developer portal and then it's successfully recreated by sigh and is using second certificate.

So it's the problem with updating provisioning, but not with creating a new provisioning.

**Comment by cwhenderson20** [comment]
I am encountering a similar issue. I am attempting to update an existing provisioning profile (which was created with sigh) to use a different certificate. This is all happening on the same machine. Sigh doesn't seem to take into account the `--cert_id` (or `-i`) argument and simply downloads the existing profile from the dev center. `--force` also makes no difference.

As @DenHeadless has mentioned, deleting the existing profile from the dev center allows sigh to create a new profile with a different cert — but the update feature doesn't seem to work by itself.
