### ISSUE TITLE
Change bundle identifier

### ISSUE THREAD

**Issue by fousa** [fastlane/sigh#126]
Hi Felix,

It would be great if it was possible to change the bundle id when resigning.

**Comment by KrauseFx** [comment]
Sure, sounds good. Do you already have experience with doing that/

**Comment by fousa** [comment]
Yeah did something similar already. 

I'll take a look at it this weekend. :)

**Comment by KrauseFx** [comment]
That's the script we're currently using: https://github.com/KrauseFx/sigh/blob/master/lib/assets/resign.sh

**Comment by fousa** [comment]
So adding BUNDLE_IDENTIFIER to the https://github.com/KrauseFx/sigh/blob/master/lib/sigh/options.rb would do the trick?

**Comment by KrauseFx** [comment]
No, the `options.rb` is only for the main action. You'll have to add it [here](https://github.com/KrauseFx/sigh/blob/master/bin/sigh#L64-L65)

**Comment by fousa** [comment]
Okay, can do that! I'll check it out and send you a PR.


-- 
Jelle

www.fousa.be
I craft awesome apps!

**Comment by webventil** [comment]
If you are changing the the bundle identifier, you also need to change it for nested apps (e.g. watch kit apps).
If a host apps has the bundle id `com.company.myapp`, the nested watch kit app has the bundle id `com.company.myapp.watchkitapp`.

By changing the bundle id to `com.company.anotherapp`the corresponding watch kit app has than changed to `com.company.anotherapp.watchkitapp`
