### ISSUE TITLE
Certificate loading error

### ISSUE THREAD

**Issue by corristo** [fastlane/sigh#141]
I'm having the following in my build log:

```
[10:33:34]: ------------------
[10:33:34]: --- Step: sigh ---
[10:33:34]: ------------------
[10:33:35]: Starting login
[10:33:38]: Successfully logged in
[10:33:38]: Fetching profiles...
unable to load certificate
80507:error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag:/SourceCache/OpenSSL098/OpenSSL098-52.30.1/src/crypto/asn1/tasn_dec.c:1341:
80507:error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error:/SourceCache/OpenSSL098/OpenSSL098-52.30.1/src/crypto/asn1/tasn_dec.c:385:Type=X509
```

I suspect that for some reason gem was build with OpenSSL from Homebrew, but that's just a guess.

Stacktrace:
```
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.10.1/lib/fastlane_core/cert_checker.rb:33:in `rescue in sha1_fingerprint': Error parsing certificate '/var/folders/zz/78r1s0xs4nzdt6b4t9gn_3x80000gn/T/cert20150721-80498-116u0tv' (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.10.1/lib/fastlane_core/cert_checker.rb:27:in `sha1_fingerprint'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.10.1/lib/fastlane_core/cert_checker.rb:8:in `is_installed?'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-0.10.1/lib/sigh/spaceship/runner.rb:69:in `block (2 levels) in fetch_profiles'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-0.10.1/lib/sigh/spaceship/runner.rb:65:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-0.10.1/lib/sigh/spaceship/runner.rb:65:in `block in fetch_profiles'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-0.10.1/lib/sigh/spaceship/runner.rb:62:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-0.10.1/lib/sigh/spaceship/runner.rb:62:in `find_all'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-0.10.1/lib/sigh/spaceship/runner.rb:62:in `fetch_profiles'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-0.10.1/lib/sigh/spaceship/runner.rb:16:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-0.10.1/lib/sigh/manager.rb:7:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/lib/fastlane/actions/sigh.rb:20:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/lib/fastlane/actions/actions_helper.rb:62:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/lib/fastlane/runner.rb:127:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/lib/fastlane/runner.rb:127:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/lib/fastlane/fast_file.rb:108:in `method_missing'
	from (eval):37:in `block (3 levels) in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/lib/fastlane/lane.rb:29:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/lib/fastlane/lane.rb:29:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/lib/fastlane/runner.rb:50:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/lib/fastlane/runner.rb:44:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/lib/fastlane/runner.rb:44:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/lib/fastlane/lane_manager.rb:36:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/bin/fastlane:35:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/bin/fastlane:124:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.11.0/bin/fastlane:130:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
```

I'm experiencing this on two different macs.

**Comment by philyates2000** [comment]
Getting the exact same error here too.

**Comment by banaslee** [comment]
+1

**Comment by KrauseFx** [comment]
This really has something to do with your OpenSSL version. Could you try updating OpenSSL to the latest version (if you haven't done it already)

**Comment by kokomo88** [comment]
it seems updating openssl doesn't solve the problem. After updating to openssl-1.0.2d_1 the error changed a bit but i think its the same as earlier.
[12:25:30]: Starting login
[12:25:33]: Successfully logged in
unable to load certificate
140735273030480:error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag:tasn_dec.c:1198:
140735273030480:error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error:tasn_dec.c:372:Type=X509
[12:25:37]: 
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.11.1/lib/fastlane_core/cert_checker.rb:33:in `rescue in sha1_fingerprint': Error parsing certificate './PNZWM99FXV.cer' (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.11.1/lib/fastlane_core/cert_checker.rb:27:in `sha1_fingerprint'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.11.1/lib/fastlane_core/cert_checker.rb:8:in `is_installed?'
	from /Library/Ruby/Gems/2.0.0/gems/cert-0.3.0/lib/cert/cert_runner.rb:31:in `block in find_existing_cert'
	from /Library/Ruby/Gems/2.0.0/gems/cert-0.3.0/lib/cert/cert_runner.rb:28:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/cert-0.3.0/lib/cert/cert_runner.rb:28:in `find_existing_cert'
	from /Library/Ruby/Gems/2.0.0/gems/cert-0.3.0/lib/cert/cert_runner.rb:16:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/cert-0.3.0/lib/cert/cert_runner.rb:4:in `launch'
	from /Library/Ruby/Gems/2.0.0/gems/cert-0.3.0/bin/cert:34:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/cert-0.3.0/bin/cert:40:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/cert-0.3.0/bin/cert:46:in `<top (required)>'
	from /usr/bin/cert:23:in `load'
	from /usr/bin/cert:23:in `<main>'

any suggestion?

**Comment by banaslee** [comment]
Getting the same thing as @kokomo88

**Comment by KrauseFx** [comment]
@kokomo88 Could you share the content of `./PNZWM99FXV.cer`?

**Comment by KrauseFx** [comment]
Or check if it is a valid `cer` file?

**Comment by kokomo88** [comment]
It looks like this is the problem:

content of PNZWM99FXV.cer : 
https://gist.github.com/kokomo88/36eff5d5d0c6e5248043

**Comment by KrauseFx** [comment]
```
				<h4>We are unable to process your request.</h4>
				<p>An unknown error occurred. Please <a href="index.action">try again</a>.
```

Oh, yes, that's definitely the issue.

**Comment by banaslee** [comment]
@KrauseFx, is there anything we can do to work around this? I couldn't understand the source of the issue.

**Comment by corristo** [comment]
I added `skip_certificate_verification: true` to `sigh` command in my `Fastfile`, looks like good temporary solution.

**Comment by banaslee** [comment]
@corristo that was also my solution. I also needed to turn my build server account to an admin account on Apple Developer page. 
@KrauseFx did this change recently? I didn't have this issue before.

**Comment by KrauseFx** [comment]
@banaslee This looks like an server-side issue on the Apple Developer Portal. 

@corristo Nice idea actually. `cert` should handle this case properly, I'll work on an update.

**Comment by mortenholmgaard** [comment]
Any news on this?

**Comment by mdubs** [comment]
I have the same issue.  I found as @banaslee said that changing to an Admin account fixes it (Developer account fails), but that is not something we want to do. Instead I did as @corristo did and added `skip_certificate_verification: true` to the sigh commands

**Comment by ssuchanowski** [comment]
My issue:
```
[01:06:36]: Starting login with user 'XXXX'
[01:06:39]: Successfully logged in
[01:06:42]: Couldn't find an existing certificate... creating a new one
[01:06:45]: $ security import /Users/sebos/Workspace/XXXX/ios/834C4SZ2BB.p12 -k '/Users/sebos/Library/Keychains/login.keychain' -T /usr/bin/codesign -T /usr/bin/security
[01:06:45]: ▸ 1 key imported.
[01:06:45]: $ security import /Users/sebos/Workspace/XXXX/ios/834C4SZ2BB.cer -k '/Users/sebos/Library/Keychains/login.keychain' -T /usr/bin/codesign -T /usr/bin/security
[01:06:45]: ▸ 1 certificate imported.
[01:06:45]: Successfully generated 834C4SZ2BB which was imported to the local machine.
[01:06:48]: Verifying the certificated is properly installed locally...

[!] Could not find the newly generated certificate installed
```

Something is wrong with .p12 file which lands in you project dir. When I try to import it (just to check if it's valid, .cert is fine) I get:

> An error has occurred. Unable to import an item.
> The contents of this item cannot be retrieved.

But when I look into Keychain then I see cert and private key.

**Comment by ssuchanowski** [comment]
I've figured out my issue using `match`

**Comment by KrauseFx** [comment]
This has probably something to do with your WWDR certificate:

> Looks like there are no local code signing identities found, you can run `security find-identity -v -p codesigning` to get this output. Check out this reply for more: https://stackoverflow.com/questions/35390072/this-certificate-has-an-invalid-issuer-apple-push-services
