### ISSUE TITLE
Failure on 'send_login_request' from Jenkins job

### ISSUE THREAD

**Issue by trvslhlt** [fastlane/sigh#151]
I am unable to successfully connect to the developer center. I have confirmed that the correct username and password are being pulled from the keychain and are available in the `login` function in "spaceship/client.rb". I am new to this toolset so I am not sure if this is a sigh, spaceship, or unrelated issue. This is the stack trace I am getting.
```
+ sigh
[37m[17:51:53]: [0mStarting login
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.3.4/lib/spaceship/portal/portal_client.rb:46:in `send_login_request': #<Faraday::Response:0x007fea946922c0> (Spaceship::Client::InvalidUserCredentialsError)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.3.4/lib/spaceship/client.rb:152:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.3.4/lib/spaceship/client.rb:50:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.3.4/lib/spaceship/portal/spaceship.rb:22:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.3.4/lib/spaceship/portal/spaceship.rb:67:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-0.10.3/lib/sigh/spaceship/runner.rb:11:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-0.10.3/lib/sigh/manager.rb:7:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-0.10.3/bin/sigh:36:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-0.10.3/bin/sigh:88:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-0.10.3/bin/sigh:95:in `<top (required)>'
	from /usr/bin/sigh:23:in `load'
	from /usr/bin/sigh:23:in `<main>'
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

In the failure log two posts are being made to "https://idmsa.apple.com/IDMSWebAuth/authenticate".
The first has parameters {appleId: <appleid>}, {appIdKey: <apikey>}, while the second has no parameters.

I have been trying to make sense of this for a few days now so any thoughts on the issue would be greatly appreciated.

**Comment by KrauseFx** [comment]
@trvslhlt Is the API key a string of letters and numbers?

**Comment by trvslhlt** [comment]
Yes the APIkey is a string with 64 numbers and letters.

**Comment by alexmaroldi** [comment]
@KrauseFx @trvslhlt  I have the same problem with **sigh** and **cert**. My API key in */tmp/spaceship_api_key.txt* is 64 numbers and letters.

**Comment by KrauseFx** [comment]
@trvslhlt @alexmaroldi and it works when you don't run it from Jenkins but run it from the command line directly?

**Comment by alexmaroldi** [comment]
@KrauseFx no, from command line I have the same error.

**Comment by asfalcone** [comment]
@trvslhlt @alexmaroldi have you been able to get this working with the latest versions?
