### ISSUE TITLE
Sigh fails to login if using non-admin AppleId

### ISSUE THREAD

**Issue by SemenovAlexander** [fastlane/sigh#169]
This issue was originally #162, but  because of my misunderstanding of process, I thought it worked fine.

So, the issue still persists, it occurs if I try to login with account, that is not admin in team. With "technical" role account - issue repeats constantly.
    
    /Library/Ruby/Gems/2.0.0/gems/spaceship-0.6.1/lib/spaceship/client.rb:240:in `parse_response': {"creationTimestamp"=>"2015-09-23T07:45:21Z", "resultCode"=>0, "userLocale"=>"en_US", "protocolVersion"=>"QH65B2", "requestId"=>nil, "requestUrl"=>"https://developer.apple.com:443//services-account/QH65B2/account/listTeams.action", "responseId"=>"05bd55e9-f238-4466-bfc9-135642873d43", "isAdmin"=>nil, "isMember"=>nil, "isAgent"=>nil, "pageNumber"=>nil, "pageSize"=>nil, "totalRecords"=>nil, "httpResponseHeaders"=>nil} (Spaceship::Client::UnexpectedResponse)
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.6.1/lib/spaceship/portal/portal_client.rb:53:in `teams'
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.6.1/lib/spaceship/portal/ui/select_team.rb:35:in `select_team'
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.6.1/lib/spaceship/portal/portal_client.rb:69:in `select_team'
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.6.1/lib/spaceship/portal/spaceship.rb:37:in `select_team'
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.6.1/lib/spaceship/portal/spaceship.rb:81:in `select_team'
    from /Library/Ruby/Gems/2.0.0/gems/sigh-0.10.7/lib/sigh/runner.rb:12:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/sigh-0.10.7/lib/sigh/manager.rb:7:in `start'
    from /Library/Ruby/Gems/2.0.0/gems/sigh-0.10.7/bin/sigh:34:in `block (2 levels) in run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/sigh-0.10.7/bin/sigh:86:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/sigh-0.10.7/bin/sigh:93:in `<top (required)>'
    from /usr/bin/sigh:23:in `load'
    from /usr/bin/sigh:23:in `<main>'

**Comment by tutipeti** [comment]
I'm getting the same unexpected response exception, sentry event ID is 9591099f4d22a94245060fefcfddb1ce for the log.

Any idea how to resolve this issue (apart from using an admin account)?

**Comment by Name-less** [comment]
@tutipeti did you find a workaround for this issue ?

**Comment by tutipeti** [comment]
@Name-less nope. But I was unable to upload a new build using `deliver` with a "technical" account as Apple has an issue there. Maybe that's related? No idea.

**Comment by KrauseFx** [comment]
Sorry, right now `sigh` and `spaceship` require Admin or Technical permission to run

**Comment by Name-less** [comment]
Ok thanks ! Perhaps it could be interesting to exit properly with an explicit error to avoid other issues opening ...

**Comment by KrauseFx** [comment]
Agreed
