### ISSUE TITLE
Repair profiles for just a single app (-a parameter)

### ISSUE THREAD

**Issue by Buju77** [fastlane/sigh#189]
As I understand it correctly, the repair command repairs *all* broken profiles. But it would be nice for the command to take in `-a, --app_identifier` parameter.

We have a lot of profiles and it takes a while to repair after revoking our distribution certificate (our certificate was somehow automatically revoked [[1]](https://forums.developer.apple.com/message/79001#79001))

And as we were in a hurry for submitting one of our app, I wanted to just repair the app we are going to submit right now.

I tried:
`sigh repair --skip_install -a com.company.ios.myapp`

but it would still repair all broken profiles. Or did I type something wrong?

**Comment by KrauseFx** [comment]
`sigh` will repair all broken profiles by default. You shouldn't have too many broken profiles anyway, so it shouldn't be an issue.

**Comment by Buju77** [comment]
but in case you want to add new devices to your existing ad hoc profile, you might want to only renew a single app (maybe because you are on a clock and don't have time to wait for all profiles to finish) :)

**Comment by danielgalasko** [comment]
+1

**Comment by danielgalasko** [comment]
Our organisation has a large number of profiles so this would be great. Currently our repair command just crashes with `/Library/Ruby/Gems/2.0.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse': 757: unexpected token at 'HTTP 400 Bad Request' (Faraday::ParsingError)` for a profile that we don't want it to touch.

**Comment by KrauseFx** [comment]
@danielgalasko this was fixed in the last release, please update using `sudo gem update spaceship`
