### ISSUE TITLE
the download all option doesn't work if you have hundreds or thousands of provision profiles

### ISSUE THREAD

**Issue by sfransen** [fastlane/sigh#199]
i try this command 
igh download_all -w -z --skip_install
 I waiting 45 minutes and I had no files

 I can do the same thing in Cupertino and it takes just 45 seconds to download all the provision profiles.
 and they have the right name not the name you make up AdHoc_com.xxxx.dddd.mobileprovision

What will it take to make this work correct and exactly work.

 This problem is worst since apple added the tv provision profiles. DAMN I hate them one for every APPID and all those managed Xcode provision profiles it make my life hell.
 Thanks

**Comment by sfransen** [comment]
note that on a small account with not many provision profiles it is fast to download the provision profiles

 I see a huge huge delay from 
message "Successfully logged in"
 to the first provision profile that is download.
 I figure out the name problem 
why would you want this name scheme I have no idea.

      #profile_name = "#{profile.class.pretty_type}_#{profile.app.bundle_id}.mobileprovision" # default name  "terrible name"
      profile_name = "#{profile.name}.mobileprovision" # default name    real name "good Name"

 I will try and debug this some more and figure out what it is doing for so long.

**Comment by KrauseFx** [comment]
Do you have Charles Proxy or any other Proxy you can use? Please run `sigh` using 
```
DEBUG=1 sigh download_all ...
```
and see which requests takes so long. `sigh` is using the Xcode API to fetch and download the provisioning profiles.

**Comment by sfransen** [comment]
I just tried that  DEBUG=1 option and it aborted right away
I don't have Charles Proxy installed on my home machine I have it on my work machine I will try again  when I get a change at work.

 Note This is on a huge account we have 5000 devices license and we have a lot of provision profiles.

DEBUG=1  sigh download_all -w -z --skip_install --username xxxxxxx@xxxxx --team_id xxxxxxxxxx

/Library/Ruby/Gems/2.0.0/gems/spaceship-0.13.0/lib/spaceship/client.rb:11: warning: already initialized constant OpenSSL::SSL::VERIFY_PEER
14:40:42]: Starting login with user  'xxxxxxx@xxxxx'

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `initialize': Connection refused - connect(2) (Faraday::ConnectionFailed)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:877:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1373:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:82:in `perform_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:32:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/connection.rb:177:in `post'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.13.0/lib/spaceship/client.rb:247:in `block in send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.13.0/lib/spaceship/client.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.13.0/lib/spaceship/client.rb:178:in `with_retry'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.13.0/lib/spaceship/client.rb:246:in `send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.13.0/lib/spaceship/client.rb:222:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.13.0/lib/spaceship/portal/portal_client.rb:34:in `send_login_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.13.0/lib/spaceship/client.rb:160:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.13.0/lib/spaceship/client.rb:54:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.13.0/lib/spaceship/portal/spaceship.rb:22:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.13.0/lib/spaceship/portal/spaceship.rb:77:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.1.1/lib/sigh/download_all.rb:6:in `download_all'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.1.1/lib/sigh/manager.rb:33:in `download_all'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.1.1/bin/sigh:44:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.1.1/bin/sigh:89:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.1.1/bin/sigh:107:in `<top (required)>'
	from /usr/local/bin/sigh:23:in `load'
	from /usr/local/bin/sigh:23:in `<main>'
