### ISSUE TITLE
Feature Request: Add tvOS support

### ISSUE THREAD

**Issue by gjandrejko** [fastlane/sigh#226]

**Comment by toshi0383** [comment]
Looks like resigning (`sigh resign`) tvOS app is working for me.
Uploading to iTC was successfully after resigning.
Just FYI.

**Comment by toshi0383** [comment]
Actually, iTC complains that "This build is invalid" .
We might have to take a look...

**Comment by toshi0383** [comment]
I was resigning AdHoc to AppStore.
It turns out that AdHoc signed app should not be resigned for AppStore. AdHoc signed ipa does not include symbol map files.

```
.
├── AdHoc
│   ├── AdHoc.ipa
│   └── Payload
└── AppStore
    ├── AppStore.ipa
    ├── BCSymbolMaps
    ├── Payload
    └── Symbols
```

Is that same for iOS, too ?

**Comment by vpolouchkine** [comment]
@toshi0383 This looks like a separate discussion, can you open a new issue please?

**Comment by bassrock** [comment]
Provisioning profiles seem to have different platform types now with the addition of tvOS.  

![screen shot 2016-02-04 at 8 22 56 pm](https://cloud.githubusercontent.com/assets/1010384/12838010/22cad5c6-cb7d-11e5-9084-43e0c68c6b0d.png)

We need to be able to select the type (App Store, Ad Hoc, Development) along with the platform now, with he default most likely being iOS.  With this it should be noted that tvOS apps and iOS apps can share the same app identifier as well and is required to support universal purchase on iOS and tvOS.
