### ISSUE TITLE
How to generate a provisioning profile for adhoc?

### ISSUE THREAD

**Issue by falcon4ever** [fastlane/sigh#233]
Hi, I'm currently trying to setup fastlane to create builds for distribution through HockeyApp. The binaries should be signed with the enterprise account cert and distributed using HockeyApp (using Adhoc).

When running sigh, I'm getting the following response, but I'm not sure what I am supposed to do with 'cert'. I ran it, it creates certs but still 'sigh' won't use them.
```
bash-3.2$ sigh --adhoc

+------------+------------+
| Summary for sigh 1.2.1  |
+------------+------------+
| adhoc      | true       |
+------------+------------+

[16:21:22]: Starting login with user 'enterprise@awesomecompany.com'
[16:21:24]: Successfully logged in
[16:21:24]: Fetching profiles...
[16:21:25]: No existing profiles, creating a new one for you
/Library/Ruby/Gems/2.0.0/gems/sigh-1.2.1/lib/sigh/runner.rb:153:in `certificate_to_use': Could not find a matching code signing identity for Spaceship::Portal::ProvisioningProfile::AdHoc. You can use cert to generate one (https://github.com/fastlane/cert) (RuntimeError)
        from /Library/Ruby/Gems/2.0.0/gems/sigh-1.2.1/lib/sigh/runner.rb:97:in `create_profile!'
        from /Library/Ruby/Gems/2.0.0/gems/sigh-1.2.1/lib/sigh/runner.rb:39:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/sigh-1.2.1/lib/sigh/manager.rb:7:in `start'
        from /Library/Ruby/Gems/2.0.0/gems/sigh-1.2.1/bin/sigh:36:in `block (2 levels) in run'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
        from /Library/Ruby/Gems/2.0.0/gems/sigh-1.2.1/bin/sigh:91:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/sigh-1.2.1/bin/sigh:109:in `<top (required)>'
        from /usr/local/bin/sigh:23:in `load'
        from /usr/local/bin/sigh:23:in `<main>'
```

**Comment by KrauseFx** [comment]
```
Could not find a matching code signing identity for Spaceship::Portal::ProvisioningProfile
```

You don't have a certificate. It is recommended to use [match](https://github.com/fastlane/sigh) for easier code signing :rocket:

**Comment by brunodelgado** [comment]
@KrauseFx match link is pointing to sigh in your answer.

**Comment by KrauseFx** [comment]
Haha, thanks, updated  [match](https://github.com/fastlane/match)

**Comment by jhihguan** [comment]
@KrauseFx 
I'm encountering the same issue when `sigh` a non-exist profile(which have an Identifier already in account)
I'm using `enterprise` account so can't use match

I did a cert before and it return `find a local XXX`
than I type `sigh --force --adhoc`, boom, same issue
It won't create automatically and I have to manually create one

**Comment by jlubeck** [comment]
I'm having the same issue with an enterprise account. @jhihguan were you able to make this work?

**Comment by KrauseFx** [comment]
You basically just use [cert](https://github.com/fastlane/cert) to create a new certificate (code signing identity) for the right environment.

**Comment by jlubeck** [comment]
I was able to create the certificate just fine, but just like @jhihguan, I wasn't able to make sigh create the provisioning profile for the adhoc enterprise. That same certificate created by cert worked just fine with a provisioning profile created manually inside Apple's Dev portal.

**Comment by ricardolpd** [comment]
Hi guys i am having the same issue, as per company rules we are not allowed to generate new certificates for enterprise distribution, havent managed to build with gym an ipa using the existent certificates. Is there a way to point manually at a provisioning profile during the packaging part of gym?

**Comment by vpolouchkine** [comment]
@ricardolpd Take a look at the `--provisioning_profile_path` option. You can get the full list by running `gym help`.
