### ISSUE TITLE
Mac app store version of sigh

### ISSUE THREAD

**Issue by rickbdotcom** [fastlane/sigh#40]
Are there any plans for a Mac app store version of these tools? For the most part just changing the paths from /ios/ to /mac/ would do the trick. I just tried that on the Nomad Cupertino tools and got those to working with the Mac app store without too much trouble.

**Comment by KrauseFx** [comment]
There is already a `deliver` ticket to add Mac App Store support: https://github.com/KrauseFx/deliver/issues/39

There are plans to adding this quite soon, probably not all tools, but `deliver` and `fastlane`.

**Comment by rickbdotcom** [comment]
Hey would happen to have a timeline on when you expect to support mac app store for sigh? I'm just maintaining my own fork for this at the moment. I don't know if they way I did it jibes with your plans for this, and I need to update it with your last round of code changes.

**Comment by KrauseFx** [comment]
Sorry, can't promise an ETA for this. I'm currently not working on `sigh` for Mac. Just `deliver` and `fastlane` for Mac.

**Comment by Sega-Zero** [comment]
Any news on this?  Need `produce`, `cert` and `sigh` for DeveloperID-signed and Mac App Store apps

**Comment by KrauseFx** [comment]
@radex added Mac support to `spaceship`, which is a great first step :+1:
